version: '3.8'
services:
  web:
    build:
      context: ./
      target: production
    volumes:
      - .:/usr/src/app
    command: node app.js
    ports:
      - ":3000"
    environment:
      NODE_ENV: production
      DEBUG: nodejs-docker-express:*