version: '3.4'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
    volumes:
      - .:/usr/src/app
    command: node app.js
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DEBUG: nodejs-docker-express:*